### ISSUE TITLE
Custom routing (routes.yaml) tag filter does not work with this theme

### ISSUE THREAD

**Issue by SCDerox** [TryGhost/Ease#23]
# How to reproduce

- Make sure you are using another theme (like Casper) and edit your routes.yml (example below)
- Observe how tags are filtered correctly
- Switch to Ease
- Observe how every article - even if the filters are not correct - are showing up

# Resources
routes.yaml
```
    routes:

    collections:
      /:
        permalink: /{slug}/
        template: index
        filter: 'tag:-hash-de'
      /de/:
        permalink: /de/{slug}/
        template: index-de
        filter: 'tag:hash-de'

    taxonomies:
      tag: /tag/{slug}/
      author: /author/{slug}/
```
(from [this](https://ghost.org/docs/tutorials/multi-language-content/) tutorial) 

# Screenshots
/ with casper as theme:
![image](https://user-images.githubusercontent.com/43812987/156620966-043884c2-209e-461c-9ea3-ec8fc3005f35.png)
/ with ease as theme:
![image](https://user-images.githubusercontent.com/43812987/156621078-5f93da65-fe19-46b6-af43-e55075bde138.png)
The "Deutscher Artikel" has the `#de` tag and should therefore be hidden the same way it's hidden in the caspar theme.

I could reproduce this issue both in a production and in a development environment on completely different machines.
